### ISSUE TITLE
Indexpath is returning wrong

### ISSUE THREAD

**Issue by Pinank** [Vishal-Singh-Panwar/InfiniteScrolling#1]
I have 10 fix indexpaths and on each indexpath it should diff. color and image. So i've place a conditional block in following method

    func configuredCell(forItemAtIndexPath indexPath: IndexPath, originalIndex: Int, andData data:     InfiniteScollingData, forInfiniteScrollingBehaviour behaviour: InfiniteScrollingBehaviour) -> UICollectionViewCell { }
 

But its not returning the correct indexpath. Can any1 from here help me to out

**Comment by Vishal-Singh-Panwar** [comment]
Use `originalIndex` and let me know if it works.

**Comment by Pinank** [comment]
Its Not, Its getting fluctuated in start like from 0-5 or 0-1 and 1-2.

**Comment by Vishal-Singh-Panwar** [comment]
`originalIndex` is an `Int`. It can't be in `IndexPath` format like 0-5. Can you share the line where you are setting color?

**Comment by Pinank** [comment]
I know its Int, with 0-5 mean to say from 0th index to reverse scroll 5th index. Suppose in following manner my cells are,

0-1-2-3-4-5 

and i want it to be in,

0-1-2-3-4-5-0-1-2-3-4-5-0-1-2-3-4-5-0-1-2-3-4-5...

but when i move from 0 to 5 or 5 to 0 or from 1 to 2, its not returning the exact index value

**Comment by Vishal-Singh-Panwar** [comment]
I am not getting you. Can you share the code?

**Comment by Vishal-Singh-Panwar** [comment]
If you are trying to say that that all the indices are not getting repeated, then thats the way it has been implemented. It only adds the indices on the edges which are required for infinite scroll effect. If you have 50 rows, but at a time on screen maximum 5 rows can be displayed, than the dataset would be like below:

**Comment by Pinank** [comment]
func configuredCell(forItemAtIndexPath indexPath: IndexPath, originalIndex: Int, andData data: InfiniteScollingData, forInfiniteScrollingBehaviour behaviour: InfiniteScrollingBehaviour) -> UICollectionViewCell {
        
        let cell = cvItems.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath)
        cell.collectionviewRoomItemList!.register(UINib(nibName: "testCell", bundle: nil), forCellWithReuseIdentifier: "testCell")
        
        
        if let roomData = data as? Rooms {
            switch roomData.index {
            case 1:
                
                break
                
            case 2:
                
                break
                
            case 3:
                
                break
                
            case 4:
                
                break
                
            case 5:
                
                break
                
            case 6:
                
                break
                
            default:
                break
            }
        }
        cell.cvItems.reloadData()
        return cell
    }

**Comment by Pinank** [comment]
In my case, at a time only one cell will be visible.

**Comment by Vishal-Singh-Panwar** [comment]
you have a `UICollectionView` inside `UICollectionViewCell`?

**Comment by Pinank** [comment]
Yes, But i think it should not affect

**Comment by Vishal-Singh-Panwar** [comment]
You are updating your collectionViewCell based on `roomData.index`. Not sure how it is related to index provided by `configuredCell` method. I might need some more clarity on the issue. I think when the parent cell is reused, you are loosing the previously visible room in your child collection view. Is that your issue?

**Comment by Pinank** [comment]
Can you give me your Skype. I'll be more clear over call

**Comment by Pinank** [comment]
Corrected

func configuredCell(forItemAtIndexPath indexPath: IndexPath, originalIndex: Int, andData data: InfiniteScollingData, forInfiniteScrollingBehaviour behaviour: InfiniteScrollingBehaviour) -> UICollectionViewCell {

        let cell = cvItems.dequeueReusableCell(withReuseIdentifier: "Cell", for: indexPath)
        cell.collectionviewRoomItemList!.register(UINib(nibName: "testCell", bundle: nil), forCellWithReuseIdentifier: "testCell")

        print("--------------->",originalIndex )
            switch originalIndex {
            case 1:

                break

            case 2:

                break

            case 3:

                break

            case 4:

                break

            case 5:

                break

            case 6:

                break

            default:
                break
            }
        cell.cvItems.reloadData()
        return cell
    }

**Comment by Vishal-Singh-Panwar** [comment]
vishal.singh031

**Comment by Pinank** [comment]
Solved
